
# @name get
GET https://api-musics-mpol.onrender.com/musics


###

# @name delete
DELETE https://api-musics-mpol.onrender.com/musics/7f5ee4a5-f820-4b72-864c-4065176e84d5


###

# @name create
POST http://localhost:3332/musics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmNzAyODlhLTQ1YzAtNDFlZS05MGFkLTM4Nzc3NGU4ZmIwYiIsImlhdCI6MTY5NTM4NTYxNywiZXhwIjoxNjk1NDcyMDE3fQ.5CL0n3x-RAwEmzalhSwbvOU7mnt9XLdevf0oMPLyIMk

{
  "title": "Homenagem aos Reliquias",
  "artist": "Mc Tafarel",
  "year": 2023,
  "code": 3223221,
  "userId": "2f70289a-45c0-41ee-90ad-387774e8fb0b"
}

###

# @name update
PUT https://api-musics-mpol.onrender.com/musics/a7721030-27b3-4ae4-abf4-7a59cd185f4d
Content-Type: application/json

{
  "title": "Homenagem",
  "artist": "Mc Tafarel",
  "year": 2023,
  "code": 32231,
  "userId": "2f70289a-45c0-41ee-90ad-387774e8fb0b"
}


###

# @name create-user
POST https://api-musics-mpol.onrender.com/user/register
Content-Type: application/json

{
  "name": "alesurf13327",
  "email": "alesurf13372@gmail.com",
  "password": "2023"
}

###

# @name login
GET https://api-musics-mpol.onrender.com/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmNzAyODlhLTQ1YzAtNDFlZS05MGFkLTM4Nzc3NGU4ZmIwYiIsImlhdCI6MTY5NTM4NTYxNywiZXhwIjoxNjk1NDcyMDE3fQ.5CL0n3x-RAwEmzalhSwbvOU7mnt9XLdevf0oMPLyIMk
###

# @name create-user
POST https://api-musics-mpol.onrender.com/user/login
Content-Type: application/json

{
  "email": "alesurf13@gmail.com",
  "password": "2023"
}
