
# @name get
GET http://localhost:3332/musics?page=1&limit=30&artist=ALCIONE


###

# @name get
GET http://localhost:3332/artists?artist=AKUNDUN


###

# @name get
GET http://localhost:3332/artists


###

# @name delete
DELETE https://api-musics-mpol.onrender.com/musics/5ab95286-b051-4538-856c-4638cf5c8f7e


###

# @name create
POST http://localhost:3332/musics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmNzAyODlhLTQ1YzAtNDFlZS05MGFkLTM4Nzc3NGU4ZmIwYiIsImlhdCI6MTY5NTc1NzA3NiwiZXhwIjoxNjk1ODQzNDc2fQ.WeWY9V75-XnBhQXp3E89jOqAzx6XL0a8dN7ZU9oN3Ks

{
  "title": "sexo",
  "artist": "Mc Tafarel",
  "year": 2023,
  "code": 1,
  "userId": "2f70289a-45c0-41ee-90ad-387774e8fb0b"
}

###

# @name update
PUT https://api-musics-mpol.onrender.com/musics/a7721030-27b3-4ae4-abf4-7a59cd185f4d
Content-Type: application/json

{
  "title": "Homenagem",
  "artist": "Mc Tafarel",
  "year": 2023,
  "code": 32231,
  "userId": "2f70289a-45c0-41ee-90ad-387774e8fb0b"
}


###

# @name create-user
POST https://api-musics-mpol.onrender.com/user/register
Content-Type: application/json

{
  "name": "alesurf13327",
  "email": "alesurf13372@gmail.com",
  "password": "2023"
}

###

# @name login
GET https://api-musics-mpol.onrender.com/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmNzAyODlhLTQ1YzAtNDFlZS05MGFkLTM4Nzc3NGU4ZmIwYiIsImlhdCI6MTY5NTM4NTYxNywiZXhwIjoxNjk1NDcyMDE3fQ.5CL0n3x-RAwEmzalhSwbvOU7mnt9XLdevf0oMPLyIMk
###

# @name create-user
POST http://localhost:3332/user/login
Content-Type: application/json

{
  "email": "alesurf13@gmail.com",
  "password": "2023"
}


###

GET http://localhost:3332/search?title=deixe


###

DELETE http://localhost:3332/user/delete-table